spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alexander-Ansimov/SpringCloud-Lab/
          searchPaths: /app-configuration
    bus:
      trace:
        enabled: true

server:
  port: 9000

management:
  security:
    enabled: false