spring:
  application:
    name: Config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alexander-Ansimov/SpringCloud-Lab/
          searchPaths: /app-configuration
      #label: config
      # label is the branch


server:
  port: 9000
