spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alexander-Ansimov/SpringCloud-Lab/
          searchPaths: /app-configuration

server:
  port: 9000
