spring:
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false

testValue: 1234-00
